In [6]:
import random

In [10]:
import numpy as np

In [11]:
# Task 1
a = np.random.randint(1, 11, size=10)

In [12]:
a

array([ 8,  2,  2,  7,  9,  3,  6,  9, 10, 10])

In [17]:
# Task 2
matrix_1 = np.zeros((3, 3), dtype=int)

In [18]:
matrix_1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
# Task 3
matrix_2 = np.random.randint(1, 11, size=(5, 5))

In [20]:
matrix_2

array([[ 1,  8,  7,  8,  3],
       [ 3,  1, 10,  9,  8],
       [ 7,  9,  1, 10,  3],
       [ 1,  4,  5,  9,  5],
       [ 7,  5,  9,  9, 10]])

In [64]:
# Task 4
matrix_3 = np.random.rand(4, 4)

In [65]:
matrix_3

array([[0.67405889, 0.90936621, 0.40629583, 0.91703797],
       [0.65482098, 0.88032633, 0.95114619, 0.63703258],
       [0.32417158, 0.28811092, 0.08304635, 0.21398965],
       [0.42913324, 0.4005845 , 0.67657058, 0.10650645]])

In [21]:
# Task 5
u = np.random.randint(11, size=5)
j = np.random.randint(11, size=5)

In [22]:
u

array([ 3, 10,  6, 10,  2])

In [23]:
j

array([ 4,  1,  3,  0, 10])

In [24]:
res_1 = u + j
res_2 = u - j
res_3 = u * j

In [25]:
res_1

array([ 7, 11,  9, 10, 12])

In [26]:
res_2

array([-1,  9,  3, 10, -8])

In [108]:
res_3

array([ 0, 36, 18, 12, 16])

In [27]:
# Task 6
w = np.random.randint(11, size=7)
e = np.random.randint(11, size=7)

res_7 = np.dot(w, e)

In [28]:

res_7

240

In [90]:
# Task 7
matrix_4 = np.random.randint(1, 11, size=(2, 2)).reshape(4, 1)
matrix_5 = np.random.randint(1, 11, size=(3, 3)).reshape(1, 9)
res_8 = np.dot(matrix_4, matrix_5)

In [91]:
res_8

array([[ 4,  8,  4,  8, 10, 16,  6,  4, 18],
       [16, 32, 16, 32, 40, 64, 24, 16, 72],
       [ 6, 12,  6, 12, 15, 24,  9,  6, 27],
       [10, 20, 10, 20, 25, 40, 15, 10, 45]])

In [29]:
# Task 8
matrix_6 = np.random.randint(1, 11, size=(3, 3))
matrix_6_inv = np.linalg.inv(matrix_6)

In [30]:
matrix_6_inv

array([[-0.07142857,  0.14285714,  0.        ],
       [-0.01322751, -0.01058201,  0.11111111],
       [ 0.2037037 , -0.03703704, -0.11111111]])

In [31]:
# Task 9
matrix_7_T = np.random.rand(4, 4).T

In [32]:
matrix_7_T

array([[0.09834867, 0.88912725, 0.0043966 , 0.2028037 ],
       [0.17726094, 0.5131197 , 0.50347138, 0.9789624 ],
       [0.59909767, 0.79985728, 0.65316009, 0.45961593],
       [0.2820519 , 0.48248186, 0.5402964 , 0.71129386]])

In [33]:
# Task 10
matrix_8 = np.random.randint(1, 11, size=(3, 4))
r = np.random.randint(10, size=4)
res_9 = matrix_8.dot(r)

In [34]:
res_9

array([70, 44, 55])

In [35]:
# Task 11
matrix_9 = np.random.rand(2, 3)
t = np.random.rand(3)
res_10 = matrix_9.dot(t)

In [36]:
res_10

array([1.09525463, 1.13871425])

In [37]:
# Task 12 
matrix_10 = np.random.randint(1, 11, size=(2, 2))
matrix_11 = np.random.randint(1, 11, size=(2, 2))
res_11 = np.multiply(matrix_10, matrix_11)

In [38]:
res_11

array([[ 9,  7],
       [24, 25]])

In [39]:
# Task 13
matrix_12 = np.random.randint(1, 11, size=(2, 2))
matrix_13 = np.random.randint(1, 11, size=(2, 2))
res_12 = np.dot(matrix_10, matrix_11)

In [40]:
res_12

array([[17, 68],
       [43, 46]])

In [41]:
# Task 14
matrix_14 = np.random.randint(1, 100, size=(5, 5))
res_13 = np.sum(matrix_14)

In [42]:
res_13

1106

In [43]:
# Task 15
matrix_15 = np.random.randint(1, 11, size=(4, 4))
res_14 = matrix_15.max() - matrix_15.min()

In [44]:
res_14

9

In [51]:
# Task 16 
matrix_16 = np.random.rand(3, 3)
res_array = np.sum(matrix_16, axis=1)
res_15 = np.array([[res_array[0]], [res_array[1]], [res_array[2]]])

In [53]:
res_15

array([[0.85835747],
       [1.02217215],
       [1.16886185]])

In [57]:
# Task 17
matrix_16 = np.square(np.random.randint(1, 11, size=(3, 4)))

In [58]:
matrix_16

array([[ 9, 64, 16, 81],
       [25,  1, 81, 25],
       [36,  4, 16, 16]])

In [59]:
# Task 18
o = np.sqrt(np.random.randint(51, size=4))

In [60]:
o

array([6.55743852, 7.07106781, 7.        , 1.41421356])